### ISSUE TITLE
Static analyzer warnings

### ISSUE THREAD

**Issue by viperjbm** [camgunz/cmp#20]
cppcheck static code analysis identifies several of these warnings, they may not be truly something to be concerned with but thought I would let you know in case you would like to update the source to take action on what it identified.

All of the warnings came from "test.c" and there were many so I'll just post one of them as an example.  If you want a list of the rest let me know.

example:
unchanged   test/test.c 1263    warning staticStringCompare false   Unnecessary comparison of static strings.

**Comment by camgunz** [comment]
I'll have a look at it, thanks!

**Comment by camgunz** [comment]
test.c is dead (long live test.c!), so this problem has resolved itself :)
