### ISSUE TITLE
Non buffered IO 

### ISSUE THREAD

**Issue by bsergean** [camgunz/cmp#25]
Hi there,

I'm trying to use your library in a signal handler, and using FILE* / stdio in signal handlers is not recommended. I don't know if there would be any problem in stuffing an integer to represent a file descriptor into the void* parameter that cmp_init expect as its second argument, and in casting the void* pointer passed back in the write callback back into a file descriptor / an integer.

This is not great as pointers can be 64 bits, it feels like a hack etc... maybe a new interface to work with non buffered IO would be convenient to have. Any thoughts ? New interface would take an int to represent a file descriptor maybe ?

Thanks !

**Comment by camgunz** [comment]
The way I see it, you have a couple options.

1. You can figure out how to store an integer in a pointer on your supported platforms.  I don't think there's a portable way to do it.  In fairness, unless you have 2 billion file descriptors, the 32/64 bit thing won't bite you, so there's probably not a lot of danger there anyway.

2. You can store the address of the file descriptor as the void pointer.  This is probably what I would do.

I could be missing something (I'm vacationing and not super focused); if I haven't really addressed your issue just let me know.

**Comment by bsergean** [comment]
Option 2 sounds good to me, it's embarrassing I didn't think about it.

Thanks, and enjoy your vacations !
