### ISSUE TITLE
Static Analysis warnings

### ISSUE THREAD

**Issue by DaelDe** [camgunz/cmp#26]
First thank you for the excellent library :)

In cmp.c there are a lot of warnings reported by our analysis tool. See screenshot. The line numbers may not match, but the function names are mentioned.
![cmp_issues](https://cloud.githubusercontent.com/assets/18593867/16977809/b49dd81e-4e58-11e6-9648-b8d70e4631e5.png)

Can you please evaluate if there is any problem with these implicit conversions? It would also be nice if you can cast accordingly to show your intention.

**Comment by client9** [comment]
Hello,

These are "ordinary" compiler warnings, and can be ignored (you can whitelist them).

The intention is made clear by the name and goal of the function -- they intentionally lose precision.

Up to @camgunz if he wants to add casts.

**Comment by DaelDe** [comment]
I agree. However, they are valid warnings and if the loss of precision is intentionally, you can make this explicit with a cast. Otherwise static analysis tools will never get the idea.

For us it is a good practice to enable all compiler warnings and treat them as errors, this is not possible with cmp.

**Comment by client9** [comment]
ah ok.
well I'm sure @camgunz  would welcome a pull request :-)

**Comment by camgunz** [comment]
Yeah there's two approaches.  Either you make those functions take the "correct" fixed-width type and use casts in your app code, or you put the casts in the functions.  I'm not happy about either, but much as I try and rationalize it, the casts are correct and they should go in CMP.  I'll take a PR, i'm ultra-busy so I won't get to it for a while (see other PRs/issues for evidence) but if someone else does it I'll merge it :)

**Comment by antoinealb** [comment]
Personally I think the best approach would be to have the functions take the correct-width type, to create as little surprise to the library user as possible ("Why is my int truncated?").

**Comment by camgunz** [comment]
Yeah now that I think about it, there are the higher-level functions that will discern which type to use depending upon the input, so I think it's fine to change these to take the proper type.  Let's do that instead of casts.

**Comment by DaelDe** [comment]
Sorry, I am not able to follow.
The methods already take the correct bit width type! The warnings arise from the fact that mesagepack is doing variable length encoding for integers, whch is nice. 
So, if you have code like this:

```
bool cmp_write_sint(cmp_ctx_t *ctx, int64_t d) {
  ...  
 if (d >= (-2147483647 - 1))
    return cmp_write_s32(ctx, d);

  return cmp_write_s64(ctx, d);
}
```

So, it is totally fine that cmp_write_s32 takes a 32 bit integer. the line before the range is actually checked and therefore it is safe to cast to show this intention to compilers.
This is why I think casts are the correct solution here.

**Comment by camgunz** [comment]
Sorry I've just been half-assing it in this thread.  I'll try and address this properly now.

Let's use this as an example:

```c
bool cmp_write_integer(cmp_ctx_t *ctx, int64_t d) {
  if (d >= 0)
    return cmp_write_uinteger(ctx, d);
  if (d >= -32)
    return cmp_write_nfix(ctx, d);
  if (d >= -128)
    return cmp_write_s8(ctx, d);
  if (d >= -32768)
    return cmp_write_s16(ctx, d);
  if (d >= (-2147483647 - 1))
    return cmp_write_s32(ctx, (int32_t) d);

  return cmp_write_s64(ctx, d);
}
```

We can't change the signature of `cmp_write_integer` here.  The whole point of that function is to take any size integer and serialize it using the smallest CMP type that will contain its magnitude.  The only options here are:

- Change `cmp_write_s8`, `cmp_write_s16`, etc. to take `int64_t`
  - Pro: Easy, no ugly casts
  - Con: Just shoves the truncation problem further down the pipe
- Add casts to the above calls: `cmp_write_s8(ctx, (int8_t)d)`
  - Pro: Correct
  - Con: Ugly
- Ignore the analyzer
  - Pro: Super easy
  - Con: For projects that use (either optional or mandatory) analyzers, this is either unacceptable or a big painful process of adding analyzer exceptions

I wish there were a "Correct, Beautiful" option but there isn't, but in the absence of beauty correctness should still win out.  Therefore I agree with @DaelDe: casts are the solution here, and I'll take a PR for it.

**Comment by DaelDe** [comment]
PR added :-)

**Comment by camgunz** [comment]
Merged, thanks a million :)
