### ISSUE TITLE
Incomplete header file

### ISSUE THREAD

**Issue by mateuszj** [camgunz/cmp#30]
In my C89 build I found out that cmp.h cannot work standalone. Please add following header files:

`#include <stdbool.h>`
`#include <stddef.h>`
`#include <stdint.h>`

to cmp.h

**Comment by m-wichmann** [comment]
This was already discussed and dismissed by @camgunz in #22.

**Comment by camgunz** [comment]
Yeah this is something I've decided against, but it comes up often enough that I may build a "design decisions" doc or something.  I'll close this but, thanks for your input @mateuszj!
