### ISSUE TITLE
re-enable C89 support

### ISSUE THREAD

**Issue by client9** [camgunz/cmp#36]
Hello!

Thanks for such a high quality library!

Unfortunately, latest has a problem for me:

```
21:38:25 cmp.c: In function 'cmp_write_float':
21:38:25 cmp.c:421: error: 'for' loop initial declaration used outside C99 mode
21:38:25 cmp.c: In function 'cmp_write_double':
21:38:25 cmp.c:439: error: 'for' loop initial declaration used outside C99 mode
```

I sadly have to use C89 for some older plugins and/or I can't add a flag to turn on C99 mode.   Could we pull out the variable from the for loop?  I know it is gross.

Happy to provide a patch as well.

regards,

nickg

**Comment by client9** [comment]
change occurred here:
https://github.com/camgunz/cmp/commit/eb3dc5893b8e4b3a023f29158aef0dd4c5984f0c#diff-8857e1c3f7ad9c56f5c4cfeb9d9966f0

**Comment by slact** [comment]
+1 for gross C89 support. I bundle cmp with an nginx module that gets built on who knows what compilers. Didn't upgrade to the latest version because of this.

**Comment by antoinealb** [comment]
I opened a pull request (#37) that contains a fix for this issue.

**Comment by camgunz** [comment]
Sure I'll merge it when I get a few (thanks @antoinealb )
