### ISSUE TITLE
Enable Travis-CI.org to catch compiler issues (C89, future gcc warnings etc)

### ISSUE THREAD

**Issue by client9** [camgunz/cmp#39]
Hello again,

thanks for all the recent patches and improvements.

RE: c89 support  https://github.com/camgunz/cmp/issues/36

How can we prevent this (and other compiler gotchas) in the future?  I don't know your workflow but I can guess you might be a *busy guy*.

I propose setting up https://travis-ci.org  for this project that that will compile `camgunz/cmp` in a few ways (-std=c89 -Wal -Wextra -Werr) and maybe with Clang and it's static analyzer and beep if warnings occur.

I can set this up as a fork+PR  but in the end you'll have to be comfortable with travis-ci.org having access to your repo.

Regards,

n

**Comment by antoinealb** [comment]
I think Travis-CI only has a read access to the repository, so I don't know why it would be uncomfortable?

As a global remark, I second the suggestion of setting up Travis for this project, it will avoid future breakages.

**Comment by client9** [comment]
travis-ci.org use to also have access to your private repos due to github's course-grain access control.  Not sure if that has been fixed or not.

**Comment by antoinealb** [comment]
According to https://docs.travis-ci.com/user/github-oauth-scopes/ this is only the case for private repositories nowadays.

**Comment by camgunz** [comment]
I'll goof around with it today

**Comment by antoinealb** [comment]
I added some code to do this in #40. Works on my travis account.

**Comment by camgunz** [comment]
Fab, you're the best.  I'm playing around w/ skipping today, we'll see how this works then.

**Comment by camgunz** [comment]
@antoinealb does it matter if it's `language: cpp` vs. `language: c` in `.travis.yml`?

**Comment by camgunz** [comment]
Ehh I'll goof around with it a lot, don't worry about it.  I guess it's time CMP grew some real infrastructure.

**Comment by antoinealb** [comment]
Comparing the two (https://docs.travis-ci.com/user/languages/cpp/ and https://docs.travis-ci.com/user/languages/c/) it seems  that the C++ builder is a strict superset of the C builder.

**Comment by client9** [comment]
wow you guys are fast!  I'll take a look once it stabilize else too many cooks in the kitchen ... once you get it working it's quite nice, but getting to that point can be a bit tricky since you can't really replicate locally.

**Comment by client9** [comment]
oh ha, the "basic travis.yml" is really that.  I'll look later tonight unless you beat me to it.

**Comment by camgunz** [comment]
Heh yeah.  I want the test suite and coverage working through Travis; that's the goal anyway.  I'm working on skipping now but I'll *probably* get through all this today.

**Comment by client9** [comment]
i can likely cut-n-paste stuff I did with client9/libinjection which compiled c code a few different ways (and as C++), and ran some static analysis tests.  For coverage I have used https://coveralls.io in the past.

**Comment by camgunz** [comment]
I started working on this and got it *mostly* working (in develop).  It ignores cmp.c, which is pretty counterproductive, but coverage for that is only around 60% (measured with lcov) anyway so not stellar.  I think I'll spend some time rounding out the tests.

**Comment by camgunz** [comment]
This is done and merged into master.  Closing.
