### ISSUE TITLE
cmp_skip_object_limit() doesn't work as documented for nested arrays

### ISSUE THREAD

**Issue by dfego** [camgunz/cmp#45]
The function `cmp_skip_object_limit()` is documented to have its limit be a limit of depth, but it doesn't work properly when you have nested arrays or maps.

For example, if one had an array of size 10 that contained 10 zero-length arrays within, that should be fine with a limit of depth 2 according to the description. However, because of the way the code is written, each time an array is encountered, the depth is increased, regardless of whether it was nested or not. As a concrete example, a diff for `test/test.c` is [attached](https://github.com/camgunz/cmp/files/2259166/diff.txt). If you apply that, build, and run `./cmptest`, the second bit of tests added fails, displaying this behavior.

Given that `cmp.c` is written without any heap allocations, I'm not sure what the solution is for tracking the depth here. One could add an arbitrarily-sized array to keep track of some data, but perhaps you can think of a more appropriate solution. Let me know if you need any more info on the specific issue!

**Comment by camgunz** [comment]
Hey, thanks for finding this!  After looking for a little while, I think this is because `depth` isn't reset after encountering a scalar.  So if you have something like `[ [] [] [] [] [] [] [] [] [] [] ]` (like your example) and your limit is `2`, the depth counter hits that by the 3rd nested array and bails.  What should happen is that after it comes out of each nested array, `depth` should be reset.  I'll work that up; if I've misunderstood or something please let me know.  And thanks again (that attached diff in particular is super helpful!) :)

**Comment by dfego** [comment]
Yeah I think you've got it right. My only thought is, how can you know when you're out of each nested array? Without allocating memory to track each level, you'll lose the previous length. As an example: `[ [1] [2] [3] [4] ]`. In this case, when you enter, you know the array has length `4`. Once you enter the first array inside, you have to track that that one has length `1`, and count elements. But you've lost track of the outer length. You can do it for a simple case with a fixed number of variables, but you can't do it for an arbitrary length without either allocating memory or having a fixed-size array (either on the stack or statically allocated). The disadvantage there is that there would be an arbitrary limit to depth, but it might be a worthwhile tradeoff.

Alternatively, if you did single allocation (let's say for an array of `ints` the length of the `limit`), you could then track the length of the current depth. I was considering a solution like that, but your code has avoided allocations thusfar, so I didn't want to propose a patch that added them now. :)

**Comment by camgunz** [comment]
Yeah you're right.  It looks like this function has to go.  I think originally the plan was to have two skipping functions -- like there are now -- but have one have no limit and the other bail immediately if it encountered a nested container.  I think I made a mistake adding the limit; there's really no way to do that w/o allocation.

I'll deprecate it and add the original non-nested function in the next version.

**Comment by camgunz** [comment]
I've made these changes and will release when it's not a weekend to try and avoid automatic build breaking while people are off.

**Comment by camgunz** [comment]
Alright, this is--at long last--complete.
