### ISSUE TITLE
A few remarks (standard headers in cmp.h + size_t return for writer)

### ISSUE THREAD

**Issue by matovitch** [camgunz/cmp#54]
Hello there,

First of all, thank you very much for this very nice small library: it's awesome! :+1: 

Just a few remarks. I've had some very minor issue since `stdint.h` and `stddef.h` were not included inside `cmp.h` is there a reason not to include them directly? Also, from what I see in `cmp.c`, you are using the writer function as if it returned `bool` and I was wondering why ask for a `size_t` here then?

Thank you again for your great library! :)

Cheers.

**Comment by camgunz** [comment]
Thanks for the kind words :)

Yeah, I used to be opinionated about this because of some previous bad experiences, but now I think it's better for header files to be self-sufficient (i.e. @fperrad's PR #53). I think I'll go ahead and merge that.

**Comment by camgunz** [comment]
Gonna close as I merged #53; feel free to check in again if that doesn't solve your issue.
