### ISSUE TITLE
Congrats on a really nice library

### ISSUE THREAD

**Issue by iphydf** [camgunz/cmp#60]
This is not an issue. This is the library I've been looking for. I was using msgpack-c because it was the one I found (many years ago), but I've been consistently disappointed with everything about it (code quality and complexity, performance, design, reaction to bug reports) to the point of about to be writing my own implementation. Then I found this one, and it's exactly as I would have designed it, so I'm super happy this exists.

Thanks for writing a high quality, readable, well-thought-out (design and implementation wise) library suitable for embedded or otherwise constrained systems.

**Comment by camgunz** [comment]
Aw thank you so much!! And thanks for putting good vibes onto the internet ⚡
